=== davidko/Mobile-C/src/mobilec.dtd
<!ELEMENT MOBILEC_MESSAGE (MESSAGE)>
<!ELEMENT MESSAGE (MOBILE_AGENT|ENCRYPTED_DATA|ENCRYPTION_DATA)>
<!ATTLIST MESSAGE
  message (MOBILE_AGENT|RETURN_MSG|ENCRYPTED_DATA|ENCRYPTION_INITIALIZE) #REQUIRED>

<!ELEMENT MOBILE_AGENT (AGENT_DATA) >
<!ELEMENT AGENT_DATA (NAME,OWNER,HOME,SENDER,WG_CODE,TASKS)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT OWNER (#PCDATA)>
<!ELEMENT HOME(#PCDATA)>
<!ELEMENT SENDER(#PCDATA)>
<!ELEMENT WG_CODE(#PCDATA)>

<!ELEMENT TASKS(TASK+,AGENT_CODE+)>
<!ATTLIST TASKS
  task CDATA #REQUIRED
  num CDATA #REQUIRED >

<!ELEMENT TASK(DATA*)>
<!ATTLIST TASK
  num ID #REQUIRED
  return CDATA #IMPLIED
  server CDATA #REQUIRED 
  code_id CDATA #IMPLIED
  persistent CDATA #IMPLIED>

<!ELEMENT DATA (ROW*)>
<!ATTLIST DATA
  name CDATA #REQUIRED
  dim CDATA #REQUIRED
  type (char|short|int|float|double) #REQUIRED>

<!ELEMENT ROW (ROW*, #PCDATA)>
<!ATTLIST ROW
  index CDATA #REQUIRED>

<!ELEMENT AGENT_CODE (#PCDATA)>
<!ATTLIST AGENT_CODE
  id ID #IMPLIED >

=== davidko/Mobile-C/demos/agent_space_functionality/agent_self_migrate/test1.xml
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
 <MESSAGE message="MOBILE_AGENT">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>mobagent1</NAME>
    <OWNER>IEL</OWNER>
    <HOME>localhost:5050</HOME>
    <TASKS task="1" num="0">
     <TASK num="0" return="no-return" complete="0" server="localhost:5051" />
     <AGENT_CODE>
      <![CDATA[
#include <stdio.h>
#include <math.h>
int main()
{
    char* str;
    printf("Hello World!\n");
    printf("This is mobagent1 from the agency at port 5050.\n");
    printf("I am performing the task on the agency at port 5051 now.\n");
    printf("%f\n", hypot(1,2)); 
    if(mc_host_port == 5050) {
      mc_MigrateAgent(mc_current_agent, "localhost", 5051);
    } else if (mc_host_port == 5051) {
      //mc_MigrateAgent(mc_current_agent, "localhost", 5050);
    }

    return 0;
}
      ]]>
     </AGENT_CODE>
    </TASKS>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>

=== davidko/Mobile-C/demos/miscellaneous/simple_send/template_trigger.xml
<?xml version="1.0"?>
<!DOCTYPE myMessage SYSTEM "mobilec.dtd">
<MOBILEC_MESSAGE>
 <MESSAGE message="MOBILE_AGENT">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>TEMPLATE_AGENT_NAME</NAME>
    <OWNER>IEL</OWNER>
    <HOME>bird2.engr.ucdavis.edu:5050</HOME>
    <TASKS task="4" num="0">
     <TASK num="0" server="TEMPLATE_SERVER1" code_id="init"
       <DATA dim="0" name="no-return" complete="0" />
     </TASK>
     <TASK num="1" server="TEMPLATE_SERVER2" code_id="0">
       <DATA dim="0" name="no-return" complete="0" />
     </TASK>
     <TASK num="2" server="TEMPLATE_SERVER3" code_id="0">
       <DATA dim="0" name="no-return" complete="0" />
     </TASK>
     <TASK num="3" server="TEMPLATE_SERVER4" code_id="1">
       <DATA dim="0" name="no-return" complete="0" />
     </TASK>
     <AGENT_CODE id="init">
      <![CDATA[
#include <stdio.h>
#define COND_1 TEMPLATE_COND1
#define COND_2 TEMPLATE_COND2
int main() {
  printf("This is TEMPLATE_AGENT_NAME.\n");
  mc_Barrier(555);
  mc_CondSignal(COND_1);
  mc_CondWait(COND_2);
  mc_CondReset(COND_2);

  mc_CondWait(COND_1);
  mc_CondReset(COND_1);
  mc_CondSignal(COND_2);
  return 0;
}
      ]]>
     </AGENT_CODE>
     <AGENT_CODE id="0">
      <![CDATA[
#include <stdio.h>
#define COND_1 TEMPLATE_COND1
#define COND_2 TEMPLATE_COND2
int main() {
  printf("This is TEMPLATE_AGENT_NAME.\n");
  mc_CondSignal(COND_1);
  mc_CondWait(COND_2);
  mc_CondReset(COND_2);

  mc_CondWait(COND_1);
  mc_CondReset(COND_1);
  mc_CondSignal(COND_2);
  return 0;
}
      ]]>
     </AGENT_CODE>
     <AGENT_CODE id="1">
      <![CDATA[
#include <stdio.h>
#define COND_1 TEMPLATE_COND1
#define COND_2 TEMPLATE_COND2
int main() {
  printf("This is TEMPLATE_AGENT_NAME.\n");
  mc_CondSignal(COND_1);
  mc_CondWait(COND_2);
  mc_CondReset(COND_2);
  return 0;
}
      ]]>
     </AGENT_CODE>
    </TASKS>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>

=== davidko/Mobile-C/demos/getting_started/bluetooth/test_gettimeofday.xml
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
 <MESSAGE message="MOBILE_AGENT">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>mobagent1</NAME>
    <OWNER>IEL</OWNER>
    <HOME>localhost:5050</HOME>
    <TASK task="1" num="0">
     <DATA dim="0" name="no-return" complete="0" server="localhost:5051">
     </DATA>
     <AGENT_CODE>
      <![CDATA[
#include <stdio.h>

struct mytime{
  unsigned long sec;
  long usec;
};

int main()
{
  struct mytime t;
  mc_gettimeofday(&t);
  printf("The time is %d, %d", t.sec, t.usec);
  printf("Hello World!\n");
  printf("This is mobagent1 from the agency at port 5050.\n");
  printf("I am performing the task on the agency at port 5051 now.\n");
  mc_gettimeofday(&t);
  printf("The time is %d, %d", t.sec, t.usec);
  return 0;
}
      ]]>
     </AGENT_CODE>
    </TASK>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
 <MESSAGE message="MOBILE_AGENT">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>mobagent1</NAME>
    <OWNER>IEL</OWNER>
    <HOME>localhost:5050</HOME>
    <TASK task="1" num="0">
     <DATA dim="0" name="no-return" complete="0" server="localhost:5051">
     </DATA>
     <AGENT_CODE>
      <![CDATA[
#include <stdio.h>

struct mytime{
  unsigned long sec;
  long usec;
};

int main()
{
  struct mytime t;
  mc_gettimeofday(&t);
  printf("The time is %d, %d", t.sec, t.usec);
  printf("Hello World!\n");
  printf("This is mobagent1 from the agency at port 5050.\n");
  printf("I am performing the task on the agency at port 5051 now.\n");
  mc_gettimeofday(&t);
  printf("The time is %d, %d", t.sec, t.usec);
  return 0;
}
      ]]>
     </AGENT_CODE>
    </TASK>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>

=== davidko/Mobile-C/demos/mobilec_c-space_functionality/cspace_misc_examples/agent.xml
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
  <MESSAGE message="MOBILE_AGENT">
    <MOBILE_AGENT>
     <AGENT_DATA>
       <NAME>mobagent1</NAME>
       <OWNER>IEL</OWNER>
       <HOME>localhost:5050</HOME>
       <TASKS task="1" num="0">
        <TASK num="0" complete="0" server="localhost:5051">
         <DATA dim="0" name="no-return" >
         </DATA>
        </TASK>
	  <AGENT_CODE>
          <![CDATA[
#include <stdio.h>
int main()
{
    printf("\nHello World! This is mobagent1 from the port 5050.\n");
    printf("I am performing the task on the agency at port 5051 now.\n");
    return 0;
}
        ]]>
        </AGENT_CODE>
      </TASKS>
      </AGENT_DATA>
    </MOBILE_AGENT>
  </MESSAGE>
</MOBILEC_MESSAGE>
